/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */
import { z as zod } from 'zod';

import { fetcher } from '../../../utils/fetcher';

/**
 * Returns list of traffic sources
 * @summary Get traffic sources
 */
export const getTrafficSourcesResponseItem = zod.object({
  id: zod.number().optional(),
  name: zod.string().optional(),
  postback_url: zod.string().optional(),
  postback_statuses: zod.array(zod.string()).optional(),
  template_name: zod.string().optional(),
  accept_parameters: zod.boolean().optional(),
  parameters: zod
    .object({
      keyword: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      cost: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      currency: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      external_id: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      creative_id: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      ad_campaign_id: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      source: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_1: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_2: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_3: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_4: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_5: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_6: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_7: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_8: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_9: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_10: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_11: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_12: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_13: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_14: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_15: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
    })
    .optional(),
  notes: zod.string().optional(),
  state: zod.string().optional(),
  created_at: zod.string().optional(),
  updated_at: zod.string().optional(),
  traffic_loss: zod.number().optional(),
  update_in_campaigns: zod.string().optional(),
});
export const getTrafficSourcesResponse = zod.array(
  getTrafficSourcesResponseItem,
);

/**
 * Creates traffic source
 * @summary Create traffic source
 */
export const postTrafficSourcesBody = zod.object({
  name: zod.string().optional(),
  postback_url: zod.string().optional(),
  postback_statuses: zod.array(zod.string()).optional(),
  template_name: zod.string().optional(),
  accept_parameters: zod.boolean().optional(),
  parameters: zod
    .object({
      keyword: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      cost: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      currency: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      external_id: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      creative_id: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      ad_campaign_id: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      source: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_1: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_2: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_3: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_4: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_5: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_6: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_7: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_8: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_9: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_10: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_11: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_12: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_13: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_14: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_15: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
    })
    .optional(),
  notes: zod.string().optional(),
  state: zod.string().optional(),
  traffic_loss: zod.number().optional(),
});

export const postTrafficSourcesResponse = zod.object({
  id: zod.number().optional(),
  name: zod.string().optional(),
  postback_url: zod.string().optional(),
  postback_statuses: zod.array(zod.string()).optional(),
  template_name: zod.string().optional(),
  accept_parameters: zod.boolean().optional(),
  parameters: zod
    .object({
      keyword: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      cost: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      currency: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      external_id: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      creative_id: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      ad_campaign_id: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      source: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_1: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_2: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_3: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_4: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_5: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_6: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_7: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_8: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_9: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_10: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_11: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_12: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_13: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_14: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_15: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
    })
    .optional(),
  notes: zod.string().optional(),
  state: zod.string().optional(),
  created_at: zod.string().optional(),
  updated_at: zod.string().optional(),
  traffic_loss: zod.number().optional(),
  update_in_campaigns: zod.string().optional(),
});

/**
 * Returns traffic source details.
 * @summary Get traffic source
 */
export const getTrafficSourcesIdParams = zod.object({
  id: zod.number().describe('Traffic source ID'),
});

export const getTrafficSourcesIdResponse = zod.object({
  id: zod.number().optional(),
  name: zod.string().optional(),
  postback_url: zod.string().optional(),
  postback_statuses: zod.array(zod.string()).optional(),
  template_name: zod.string().optional(),
  accept_parameters: zod.boolean().optional(),
  parameters: zod
    .object({
      keyword: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      cost: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      currency: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      external_id: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      creative_id: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      ad_campaign_id: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      source: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_1: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_2: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_3: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_4: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_5: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_6: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_7: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_8: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_9: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_10: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_11: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_12: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_13: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_14: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_15: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
    })
    .optional(),
  notes: zod.string().optional(),
  state: zod.string().optional(),
  created_at: zod.string().optional(),
  updated_at: zod.string().optional(),
  traffic_loss: zod.number().optional(),
  update_in_campaigns: zod.string().optional(),
});

/**
 * Updates traffic source.
 * @summary Update traffic source
 */
export const putTrafficSourcesIdParams = zod.object({
  id: zod.number().describe('Traffic source ID'),
});

export const putTrafficSourcesIdBody = zod.object({
  name: zod.string().optional(),
  postback_url: zod.string().optional(),
  postback_statuses: zod.array(zod.string()).optional(),
  template_name: zod.string().optional(),
  accept_parameters: zod.boolean().optional(),
  parameters: zod
    .object({
      keyword: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      cost: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      currency: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      external_id: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      creative_id: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      ad_campaign_id: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      source: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_1: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_2: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_3: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_4: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_5: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_6: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_7: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_8: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_9: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_10: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_11: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_12: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_13: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_14: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_15: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
    })
    .optional(),
  notes: zod.string().optional(),
  state: zod.string().optional(),
  traffic_loss: zod.number().optional(),
});

export const putTrafficSourcesIdResponse = zod.object({
  id: zod.number().optional(),
  name: zod.string().optional(),
  postback_url: zod.string().optional(),
  postback_statuses: zod.array(zod.string()).optional(),
  template_name: zod.string().optional(),
  accept_parameters: zod.boolean().optional(),
  parameters: zod
    .object({
      keyword: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      cost: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      currency: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      external_id: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      creative_id: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      ad_campaign_id: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      source: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_1: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_2: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_3: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_4: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_5: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_6: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_7: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_8: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_9: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_10: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_11: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_12: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_13: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_14: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_15: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
    })
    .optional(),
  notes: zod.string().optional(),
  state: zod.string().optional(),
  created_at: zod.string().optional(),
  updated_at: zod.string().optional(),
  traffic_loss: zod.number().optional(),
  update_in_campaigns: zod.string().optional(),
});

/**
 * Changes the state to 'deleted'.
 * @summary Delete traffic source
 */
export const deleteTrafficSourcesIdParams = zod.object({
  id: zod.number().describe('Traffic source ID'),
});

/**
 * Makes a copy of traffic source.
 * @summary Clone trafic source
 */
export const postTrafficSourcesIdCloneParams = zod.object({
  id: zod.number().describe('Traffic source ID'),
});

export const postTrafficSourcesIdCloneResponse = zod.object({
  id: zod.number().optional(),
  name: zod.string().optional(),
  postback_url: zod.string().optional(),
  postback_statuses: zod.array(zod.string()).optional(),
  template_name: zod.string().optional(),
  accept_parameters: zod.boolean().optional(),
  parameters: zod
    .object({
      keyword: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      cost: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      currency: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      external_id: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      creative_id: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      ad_campaign_id: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      source: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_1: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_2: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_3: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_4: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_5: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_6: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_7: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_8: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_9: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_10: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_11: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_12: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_13: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_14: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
      sub_id_15: zod
        .object({
          name: zod.string().optional(),
          placeholder: zod.string().optional(),
          alias: zod.string().optional(),
        })
        .optional(),
    })
    .optional(),
  notes: zod.string().optional(),
  state: zod.string().optional(),
  created_at: zod.string().optional(),
  updated_at: zod.string().optional(),
  traffic_loss: zod.number().optional(),
  update_in_campaigns: zod.string().optional(),
});
