services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: hermes-postgres
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '${DATABASE_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hermes-network
    restart: unless-stopped
    healthcheck:
      test:
        ['CMD-SHELL', 'pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}']
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: hermes-redis
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis_data:/data
    networks:
      - hermes-network
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  # pgAdmin for PostgreSQL monitoring
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: hermes-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - '5050:80'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - hermes-network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  # Backend API
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: hermes-backend
    env_file:
      - .env
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: 3000
      APP_PORT: 3000

      # Database configuration (internal container communication)
      DATABASE_TYPE: ${DATABASE_TYPE}
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_URL: postgresql://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@postgres:5432/${DATABASE_NAME}
      DATABASE_SYNCHRONIZE: ${DATABASE_SYNCHRONIZE}
      DATABASE_MAX_CONNECTIONS: ${DATABASE_MAX_CONNECTIONS}
      DATABASE_SSL_ENABLED: ${DATABASE_SSL_ENABLED}

      # Redis configuration (internal container communication)
      REDIS_HOST: redis
      REDIS_PORT: 6379

      # External API settings
      GET_LEADS_URL: ${GET_LEADS_URL}
      GET_PRODUCTS_URL: ${GET_PRODUCTS_URL}
      ADD_LEAD_URL: ${ADD_LEAD_URL}
      EXTERNAL_API_KEY: ${EXTERNAL_API_KEY}
      EXTERNAL_API_TIMEOUT: ${EXTERNAL_API_TIMEOUT}
      AFFILIATE_API_TIMEOUT: ${AFFILIATE_API_TIMEOUT}

      # JWT settings
      AUTH_JWT_SECRET: ${AUTH_JWT_SECRET}
      AUTH_JWT_TOKEN_EXPIRES_IN: ${AUTH_JWT_TOKEN_EXPIRES_IN}
      AUTH_REFRESH_SECRET: ${AUTH_REFRESH_SECRET}
      AUTH_REFRESH_TOKEN_EXPIRES_IN: ${AUTH_REFRESH_TOKEN_EXPIRES_IN}

      # Application settings
      API_PREFIX: ${API_PREFIX}
      APP_FALLBACK_LANGUAGE: ${APP_FALLBACK_LANGUAGE}
      APP_HEADER_LANGUAGE: ${APP_HEADER_LANGUAGE}

      # CORS
      FRONTEND_DOMAIN: ${FRONTEND_DOMAIN}
    ports:
      - '${BACKEND_PORT}:3000'
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - hermes-network
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'nc', '-z', '127.0.0.1', '3000']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        NODE_ENV: ${NODE_ENV}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
        NEXT_PUBLIC_FRONTEND_URL: ${NEXT_PUBLIC_FRONTEND_URL}
        API_SCHEME_URL: ${API_SCHEME_URL}
        EXTERNAL_API_KEY: ${EXTERNAL_API_KEY}
    container_name: hermes-frontend
    env_file:
      - .env
    environment:
      NODE_ENV: ${NODE_ENV}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
      NEXT_PUBLIC_FRONTEND_URL: ${NEXT_PUBLIC_FRONTEND_URL}
      API_SCHEME_URL: ${API_SCHEME_URL}
      EXTERNAL_API_KEY: ${EXTERNAL_API_KEY}
      PORT: 3000
      HOSTNAME: '0.0.0.0'
    ports:
      - '${FRONTEND_PORT}:3000'
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - hermes-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  pgadmin_data:

networks:
  hermes-network:
    driver: bridge
