services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: hermes-postgres
    env_file:
      - .env
      - backend/.env
    ports:
      - '${DATABASE_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hermes-network
    restart: unless-stopped
    healthcheck:
      test:
        ['CMD-SHELL', 'pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}']
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: hermes-redis
    env_file:
      - .env
      - backend/.env
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis_data:/data
    networks:
      - hermes-network
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  # pgAdmin for PostgreSQL monitoring
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: hermes-pgadmin
    env_file:
      - .env
      - backend/.env
    ports:
      - '${PGADMIN_PORT}:80'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - hermes-network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  # Backend API (Rules Management Only)
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: hermes-backend
    env_file:
      - .env
      - backend/.env
    ports:
      - '${BACKEND_PORT}:3000'
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - hermes-network
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'nc', '-z', '127.0.0.1', '3000']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        NODE_ENV: ${NODE_ENV:-production}
    container_name: hermes-frontend
    env_file:
      - .env
      - frontend/.env
    ports:
      - '${FRONTEND_PORT}:3000'
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - hermes-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  pgadmin_data:

networks:
  hermes-network:
    driver: bridge
