/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */
import type { AffiliateNetworkState } from './affiliateNetworkState';

export interface AffiliateNetwork {
  id?: number;
  name?: string;
  postback_url?: string;
  offer_param?: string;
  state?: AffiliateNetworkState;
  template_name?: string;
  notes?: string;
  pull_api_options?: string;
  created_at?: string;
  updated_at?: string;
  offers?: number;
}
