/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */
import type { AffiliateNetworkObject } from './affiliateNetworkObject';

export type AffiliateNetworkPut = AffiliateNetworkObject;
