/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */

export interface AffiliateNetworkObject {
  /** Affiliate network name */
  name?: string;
  /** Postback URL for the Affiliate network */
  postback_url?: string;
  /** These params are appends to offer URLs. Example, "sub1={subid}&sub2={campaign_name}" */
  offer_param?: string;
  /** User Notes for the Affiliate network */
  notes?: string;
}
