/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */

export interface BotListRequest {
  /** List of IPs. Example, 1.2.3.4
2.3.4.5 */
  value: string;
}
