/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */

/**
 * Campaign State
 */
export type CampaignRequestState =
  (typeof CampaignRequestState)[keyof typeof CampaignRequestState];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CampaignRequestState = {
  active: 'active',
  disabled: 'disabled',
  deleted: 'deleted',
} as const;
