/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */

/**
 * 's' for flows. 'sl' for flows and landing pages. 'slo' for flows, landing pages and offers.
 */
export type CampaignBindVisitors =
  (typeof CampaignBindVisitors)[keyof typeof CampaignBindVisitors];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CampaignBindVisitors = {
  s: 's',
  sl: 'sl',
  slo: 'slo',
} as const;
