/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */

/**
 * Cost Type
 */
export type CampaignRequestCostType =
  (typeof CampaignRequestCostType)[keyof typeof CampaignRequestCostType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CampaignRequestCostType = {
  CPC: 'CPC',
  CPUC: 'CPUC',
  CPM: 'CPM',
} as const;
