/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */

export type CampaignState = (typeof CampaignState)[keyof typeof CampaignState];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CampaignState = {
  active: 'active',
  disabled: 'disabled',
  deleted: 'deleted',
} as const;
