/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */

/**
 * Set 'weight' to enable split-testing the flows.
 */
export type CampaignType = (typeof CampaignType)[keyof typeof CampaignType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CampaignType = {
  position: 'position',
  weight: 'weight',
} as const;
