/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */

/**
 * Flow  Rotation Type
 */
export type CampaignRequestType =
  (typeof CampaignRequestType)[keyof typeof CampaignRequestType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CampaignRequestType = {
  position: 'position',
  weight: 'weight',
} as const;
