/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */
import type { FilterCostRequest } from './filterCostRequest';

export interface CampaignCostRequest {
  /** Start date and time. For example, "2017-09-10 20:10" */
  start_date: string;
  /** End date and time. For example, "2017-09-10 20:10" */
  end_date: string;
  /** Timezone for the time range. For example, "Europe/Madrid". */
  timezone: string;
  /** Cost for the time range. For example, "19.22". */
  cost: string;
  /** Currency of cost. For example "EUR". */
  currency: string;
  /** Apply new costs to unique clicks only. */
  only_campaign_uniques?: boolean;
  filters?: FilterCostRequest;
}
