/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */
import type { RangeRequest } from './rangeRequest';
import type { FilterRequest } from './filterRequest';
import type { SortRequest } from './sortRequest';

export interface ClickRequest {
  range?: RangeRequest;
  /** Clicks Request Limit. Either 'limit' or 'range' Parameters are a Must. */
  limit?: number;
  /** Offset rows */
  offset?: number;
  columns?: string[];
  filters?: FilterRequest[];
  sort?: SortRequest[];
}
