/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */
import type { FilterCostRequest } from './filterCostRequest';

export interface ClicksUpdateCostsPayload {
  /** Start date and time, e.g., “2017-09-10 20:10” */
  start_date: string;
  /** End date and time, e.g., “2017-09-10 20:10” */
  end_date: string;
  /** Cost value, e.g., 19.22 */
  cost: number;
  filters?: FilterCostRequest;
}
