/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */
import type { RangeRequest } from './rangeRequest';
import type { FilterRequest } from './filterRequest';
import type { SortRequest } from './sortRequest';

export interface ConversionRequest {
  range?: RangeRequest;
  /** Limit result */
  limit?: number;
  /** Offset for results */
  offset?: number;
  columns?: string[];
  filters?: FilterRequest[];
  sort?: SortRequest[];
}
