/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */
import type { DomainState } from './domainState';

export interface Domain {
  id?: number;
  name?: string;
  network_status?: string;
  default_campaign?: string;
  default_campaign_id?: number;
  state?: DomainState;
  created_at?: string;
  updated_at?: string;
  catch_not_found?: boolean;
  campaigns_count?: number;
  ssl_redirect?: boolean;
  allow_indexing?: boolean;
  admin_dashboard?: boolean;
  cloudflare_proxy?: boolean;
  group_id?: number;
  group?: string;
  is_ssl?: boolean;
  dns_provider?: string;
  error_solution?: string;
  status?: string;
}
