/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */

export interface DomainRequest {
  /** Domain name */
  name?: string;
  /** Run campaign on the domain */
  default_campaign_id?: number;
  /** Group ID */
  group_id?: string;
  /** Catch the traffic of non-existent URLs */
  catch_not_found?: boolean;
  /** Notes for the domain */
  notes?: string;
  /** Force browsers to redirect from HTTP to HTTPS */
  ssl_redirect?: boolean;
  /** Allow robots to index the domain content */
  allow_indexing?: boolean;
  /** Allow access to admin dashboard */
  admin_dashboard?: boolean;
}
