/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */
import type { FacebookProxyProtocol } from './facebookProxyProtocol';

export type FacebookProxy = {
  /** Protocol */
  protocol?: FacebookProxyProtocol;
  /** Proxy address */
  address?: string;
  /** Proxy port */
  port?: number;
  /** Proxy login */
  login?: string;
  /** Proxy password */
  password?: string;
};
