/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */

/**
 * Protocol
 */
export type FacebookProxyProtocol =
  (typeof FacebookProxyProtocol)[keyof typeof FacebookProxyProtocol];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FacebookProxyProtocol = {
  http: 'http',
  https: 'https',
  socks5: 'socks5',
} as const;
