/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */
import type { FacebookProxy } from './facebookProxy';

export interface Facebook {
  /** Intergration ID */
  id?: number;
  /** The integration name */
  integration?: string;
  /** Use proxy */
  proxy_enabled?: boolean;
  /** The integration name */
  name?: string;
  /** Facebook account ID */
  ad_account_id?: string;
  /** Facebook token */
  token?: string;
  /** Last error */
  last_error?: string;
  /** Error message from facebook */
  last_raw_error?: string;
  proxy?: FacebookProxy;
}
