/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */
import type { FilterStreamRequestMode } from './filterStreamRequestMode';

export interface FilterStreamRequest {
  /** Flow filter ID. Provide it if you update the filter. */
  id?: number;
  /** Flow filter name, see 'retrive-stream-filters' section */
  name: string;
  /** Filter mode */
  mode: FilterStreamRequestMode;
  /** Flow payload. This field contains values for filters. For example, for a "keyword" Filter an Array ["value1", "value2"] must be provided */
  payload?: string[];
}
