/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */

/**
 * Send a key-value object to apply filters to clicks. For example, {"sub_id_1": "1,2,3", "source": "site.ru"}.
 */
export interface FilterCostRequest {
  keyword?: string;
  external_id?: string;
  creative_id?: string;
  ad_campaign_id?: string;
  source?: string;
  sub_id_1?: string;
  sub_id_2?: string;
  sub_id_3?: string;
  sub_id_4?: string;
  sub_id_5?: string;
  sub_id_6?: string;
  sub_id_7?: string;
  sub_id_8?: string;
  sub_id_9?: string;
  sub_id_10?: string;
  sub_id_11?: string;
  sub_id_12?: string;
  sub_id_13?: string;
  sub_id_14?: string;
  sub_id_15?: string;
  sub_id_16?: string;
  sub_id_17?: string;
  sub_id_18?: string;
  sub_id_19?: string;
  sub_id_20?: string;
  sub_id_21?: string;
  sub_id_22?: string;
  sub_id_23?: string;
  sub_id_24?: string;
  sub_id_25?: string;
  sub_id_26?: string;
  sub_id_27?: string;
  sub_id_28?: string;
  sub_id_29?: string;
  sub_id_30?: string;
}
