/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */
import type { FilterRequestExpression } from './filterRequestExpression';

export interface FilterRequest {
  /** Name of the field */
  name: string;
  /** One of the available operators (<a href="#operators">operators</a>)
   */
  operator: string;
  /** Expression for the filter */
  expression?: FilterRequestExpression;
}
