/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */

export type GetCampaignsParams = {
  /**
   * The number of campaigns to skip before starting to collect the result set.
   */
  offset?: number;
  /**
   * The numbers of campaigns to return.
   */
  limit?: number;
};
