/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */

export type GetDomainsIp200 = {
  /** IPv4 address */
  ipv4?: string;
  /** IPv6 address */
  ipv6?: string;
};
