/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */

export type GetGroupsType = (typeof GetGroupsType)[keyof typeof GetGroupsType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetGroupsType = {
  campaigns: 'campaigns',
  offers: 'offers',
  landings: 'landings',
  domains: 'domains',
} as const;
