/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */

export type GetLandingPagesIdGetFileParams = {
  /**
   * File path. It must be relative, i.e. `order/success.html`.
   */
  path: string;
};
