/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */

export type GetLogsTypeParams = {
  /**
   * Limit rows
   */
  limit: number;
  /**
   * Offset
   */
  offset?: number;
  /**
   * Search query
   */
  query?: string;
};
