/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */
import type { GroupRequestType } from './groupRequestType';

export interface GroupRequest {
  /** Group name */
  name?: string;
  /** Group type */
  type?: GroupRequestType;
}
