/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */

/**
 * Group type
 */
export type GroupRequestType =
  (typeof GroupRequestType)[keyof typeof GroupRequestType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GroupRequestType = {
  campaigns: 'campaigns',
  offers: 'offers',
  landings: 'landings',
  domains: 'domains',
} as const;
