/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */
import type { LabelRequestPostItems } from './labelRequestPostItems';

export interface LabelRequestPost {
  /** Campaign ID */
  campaign_id: number;
  /** <style>
  .list-flex {
    display: flex;
    list-style: none;
    flex-wrap: wrap;
  }
  .list-flex li {
    width: 200px;
  }
</style>
List of available ref names:
<ul class="list-flex">
<li class="level1"><div class="li"> ip</div>
</li>
<li class="level1"><div class="li"> source</div>
</li>
<li class="level1"><div class="li"> ad_campaign_id</div>
</li>
<li class="level1"><div class="li"> creative_id</div>
</li>
<li class="level1"><div class="li"> keyword</div>
</li>
<li class="level1"><div class="li"> ad_campaign_idn</div>
</li>
<li class="level1"><div class="li"> sub_id_1..10</div>
</li>
</ul>
 */
  ref_name: string;
  items: LabelRequestPostItems;
}
