/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */

export type LandingStreamRequestState =
  (typeof LandingStreamRequestState)[keyof typeof LandingStreamRequestState];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LandingStreamRequestState = {
  active: 'active',
  disabled: 'disabled',
} as const;
