/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */
import type { LandingStreamRequestState } from './landingStreamRequestState';

export interface LandingStreamRequest {
  /** Landing Page ID */
  landing_id: number;
  /** Share among others */
  share: number;
  state?: LandingStreamRequestState;
}
