/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */
import type { LandingRequestActionPayload } from './landingRequestActionPayload';
import type { LandingRequestState } from './landingRequestState';
import type { LandingRequestLandingType } from './landingRequestLandingType';
import type { LandingRequestActionType } from './landingRequestActionType';

export interface LandingRequest {
  /** Landing page name */
  name?: string;
  /** Action payload */
  action_payload?: LandingRequestActionPayload;
  /** Group ID */
  group_id?: string;
  state?: LandingRequestState;
  /** Landing page type */
  landing_type?: LandingRequestLandingType;
  /** Action type */
  action_type?: LandingRequestActionType;
  /** URL */
  url?: string;
  /** ZIP-file encoded to base64. */
  archive?: string;
  /** Notes */
  notes?: string;
}
