/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */
import type { LandingActionPayload } from './landingActionPayload';
import type { LandingActionOptions } from './landingActionOptions';

export interface Landing {
  id?: number;
  landing_type?: string;
  action_type?: string;
  action_payload?: LandingActionPayload;
  action_options?: LandingActionOptions;
  name?: string;
  group_id?: number;
  offer_count?: number;
  notes?: string;
  state?: string;
  created_at?: string;
  updated_at?: string;
  archive?: string;
  local_path?: string;
  preview_path?: string;
}
