/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */

export type LandingRequestState =
  (typeof LandingRequestState)[keyof typeof LandingRequestState];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LandingRequestState = {
  active: 'active',
  disabled: 'disabled',
  deleted: 'deleted',
} as const;
