/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */

export interface LandingStream {
  id?: number;
  stream_id?: number;
  landing_id?: number;
  state?: string;
  share?: number;
  created_at?: string;
  updated_at?: string;
}
