/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */
import type { LandingRequestActionPayloadOneOf } from './landingRequestActionPayloadOneOf';

/**
 * Action payload
 */
export type LandingRequestActionPayload =
  | string
  | LandingRequestActionPayloadOneOf;
