/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */

/**
 * Landing page type
 */
export type LandingRequestLandingType =
  (typeof LandingRequestLandingType)[keyof typeof LandingRequestLandingType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LandingRequestLandingType = {
  local: 'local',
  external: 'external',
  preloaded: 'preloaded',
  action: 'action',
} as const;
