/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */

/**
 * Action type
 */
export type LandingRequestActionType =
  (typeof LandingRequestActionType)[keyof typeof LandingRequestActionType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LandingRequestActionType = {
  local_file: 'local_file',
  http: 'http',
  curl: 'curl',
  status404: 'status404',
  show_text: 'show_text',
  show_html: 'show_html',
} as const;
