/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */

export type OfferStreamRequestState =
  (typeof OfferStreamRequestState)[keyof typeof OfferStreamRequestState];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OfferStreamRequestState = {
  active: 'active',
  disabled: 'disabled',
} as const;
