/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */
import type { OfferActionPayloadOneOf } from './offerActionPayloadOneOf';

export type OfferActionPayload = string | OfferActionPayloadOneOf;
