/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */
import type { OfferRequestActionPayloadOneOf } from './offerRequestActionPayloadOneOf';

/**
 * Action payload or URL
 */
export type OfferRequestActionPayload = string | OfferRequestActionPayloadOneOf;
