/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */

/**
 * Payout type
 */
export type OfferRequestPayoutType =
  (typeof OfferRequestPayoutType)[keyof typeof OfferRequestPayoutType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OfferRequestPayoutType = {
  CPA: 'CPA',
  CPC: 'CPC',
} as const;
