/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */
import type { OfferRequestActionPayload } from './offerRequestActionPayload';
import type { OfferRequestPayoutType } from './offerRequestPayoutType';
import type { OfferRequestState } from './offerRequestState';

export interface OfferRequest {
  /** Offer name */
  name?: string;
  /** Offer group ID */
  group_id?: number;
  /** Offer Type ('local'/'external'/'preloaded'/'action') */
  offer_type?: string;
  /** Action or redirect type */
  action_type?: string;
  /** Action payload or URL */
  action_payload?: OfferRequestActionPayload;
  /** Affiliate network ID */
  affiliate_network_id?: number;
  /** Payout value */
  payout_value?: number;
  /** Payout currency */
  payout_currency?: string;
  /** Payout type */
  payout_type?: OfferRequestPayoutType;
  /** Offer State */
  state?: OfferRequestState;
  /** If true, offer receives payout value from postback */
  payout_auto?: boolean;
  /** Allow offer to get upsells */
  payout_upsell?: boolean;
  /** Country codes (i.g, ["US", "DE", "JP"]) */
  country?: string[];
  /** Notes */
  notes?: string;
  /** ZIP-file encoded to base64 */
  archive?: string;
  /** Turn on that feature if the offer limit conversions per day */
  conversion_cap_enabled?: boolean;
  /** Daily limit of conversions, after which the tracker will send traffic to another offer */
  daily_cap?: number;
  /** Which timezone is being used by the Affiliate network for calculating conversions, e.g. UTC or Europe/Madrid */
  conversion_timezone?: string;
  /** Offer id, where to send traffic when daily limit is reached */
  alternative_offer_id?: number;
}
