/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */
import type { OfferStreamRequestState } from './offerStreamRequestState';

export interface OfferStreamRequest {
  /** Offer ID */
  offer_id: number;
  /** Percentage of Traffic Sent to This Offer */
  share: number;
  state?: OfferStreamRequestState;
}
