/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */

/**
 * Offer State
 */
export type OfferRequestState =
  (typeof OfferRequestState)[keyof typeof OfferRequestState];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OfferRequestState = {
  active: 'active',
  deleted: 'deleted',
} as const;
