/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */
import type { DomainRequest } from './domainRequest';
import type { DomainCreateRequired } from './domainCreateRequired';

export type PostDomainsBody = DomainRequest & DomainCreateRequired;
