/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */
import type { GroupRequest } from './groupRequest';
import type { GroupCreateRequired } from './groupCreateRequired';

export type PostGroupsBody = GroupRequest & GroupCreateRequired;
