/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */
import type { OfferRequest } from './offerRequest';
import type { OfferCreateRequired } from './offerCreateRequired';

export type PostOffersBody = OfferRequest & OfferCreateRequired;
