/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */
import type { CampaignRequest } from './campaignRequest';
import type { CampaignCreateRequired } from './campaignCreateRequired';

export type PostCampaignsBody = CampaignRequest & CampaignCreateRequired;
