/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */
import type { LandingRequest } from './landingRequest';
import type { LandingCreateRequired } from './landingCreateRequired';

export type PostLandingPagesBody = LandingRequest & LandingCreateRequired;
