/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */
import type { Facebook } from './facebook';

export type PutIntegrationsFacebookId200 = {
  data?: Facebook;
};
