/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */

export type PutOffersIdUpdateFileParams = {
  /**
   * File path
   */
  path: string;
  /**
   * File cointent
   */
  data: string;
};
