/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */

export interface RangeRequest {
  /** Start Date, e.g., '2017-09-10' */
  from?: string;
  /** End Date, e.g., '2017-09-10' */
  to?: string;
  /** E.g., Europe/Madrid */
  timezone?: string;
  /** One of the intervals can be used: today, yesterday, 7_days_ago, first_day_of_this_week, 1_month_ago, first_day_of_this_month, 1_year_ago, first_day_of_this_year, all_time
   */
  interval?: unknown;
}
