/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */
import type { RangeRequest } from './rangeRequest';
import type { FilterRequest } from './filterRequest';
import type { SortRequest } from './sortRequest';

export interface ReportsRequest {
  range?: RangeRequest;
  dimensions?: string[];
  measures?: string[];
  /** Filters can contain OR and AND logical operators. */
  filters?: FilterRequest[];
  sort?: SortRequest[];
}
