/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */

export type S2SPostbackStatusesItem =
  (typeof S2SPostbackStatusesItem)[keyof typeof S2SPostbackStatusesItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const S2SPostbackStatusesItem = {
  lead: 'lead',
  sale: 'sale',
  rejected: 'rejected',
  rebill: 'rebill',
} as const;
