/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */

/**
 * Request method
 */
export type S2SPostbackMethod =
  (typeof S2SPostbackMethod)[keyof typeof S2SPostbackMethod];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const S2SPostbackMethod = {
  GET: 'GET',
  POST: 'POST',
} as const;
