/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */
import type { S2SPostbackMethod } from './s2SPostbackMethod';
import type { S2SPostbackStatusesItem } from './s2SPostbackStatusesItem';

export interface S2SPostback {
  /** Campaign ID */
  campaign_id?: number;
  /** Postback ID */
  id?: number;
  /** Request method */
  method?: S2SPostbackMethod;
  /** Conversion status */
  statuses?: S2SPostbackStatusesItem[];
  /** Postback URL */
  url?: string;
}
