/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */
import type { SourceParameters } from './sourceParameters';

export interface Source {
  id?: number;
  name?: string;
  postback_url?: string;
  postback_statuses?: string[];
  template_name?: string;
  accept_parameters?: boolean;
  parameters?: SourceParameters;
  notes?: string;
  state?: string;
  created_at?: string;
  updated_at?: string;
  traffic_loss?: number;
  update_in_campaigns?: string;
}
