/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */
import type { PlaceholderObject } from './placeholderObject';

export interface SourceParameters {
  keyword?: PlaceholderObject;
  cost?: PlaceholderObject;
  currency?: PlaceholderObject;
  external_id?: PlaceholderObject;
  creative_id?: PlaceholderObject;
  ad_campaign_id?: PlaceholderObject;
  source?: PlaceholderObject;
  sub_id_1?: PlaceholderObject;
  sub_id_2?: PlaceholderObject;
  sub_id_3?: PlaceholderObject;
  sub_id_4?: PlaceholderObject;
  sub_id_5?: PlaceholderObject;
  sub_id_6?: PlaceholderObject;
  sub_id_7?: PlaceholderObject;
  sub_id_8?: PlaceholderObject;
  sub_id_9?: PlaceholderObject;
  sub_id_10?: PlaceholderObject;
  sub_id_11?: PlaceholderObject;
  sub_id_12?: PlaceholderObject;
  sub_id_13?: PlaceholderObject;
  sub_id_14?: PlaceholderObject;
  sub_id_15?: PlaceholderObject;
}
