/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */
import type { StreamObjectType } from './streamObjectType';
import type { StreamObjectActionOptions } from './streamObjectActionOptions';
import type { StreamObjectState } from './streamObjectState';
import type { StreamObjectSchema } from './streamObjectSchema';
import type { FilterStreamRequest } from './filterStreamRequest';
import type { TriggersStreamRequest } from './triggersStreamRequest';
import type { LandingStreamRequest } from './landingStreamRequest';
import type { OfferStreamRequest } from './offerStreamRequest';

export interface StreamObject {
  /** Campaign ID */
  campaign_id?: number;
  /** Flow type */
  type?: StreamObjectType;
  /** Flow name */
  name?: string;
  /** Position of a flow among other flows. */
  position?: number;
  /** Flow weight. */
  weight?: number;
  /** Action options. */
  action_options?: StreamObjectActionOptions;
  /** Comments or notes for the flow */
  comments?: string;
  /** State of the flow */
  state?: StreamObjectState;
  /** Action to perform (see 'Retrieve available flow action types') */
  action_type?: string;
  schema?: StreamObjectSchema;
  /** Flow saves clicks (true/false) */
  collect_clicks?: boolean;
  /** Use 'OR' operator between filters */
  filter_or?: boolean;
  filters?: FilterStreamRequest[];
  triggers?: TriggersStreamRequest[];
  landings?: LandingStreamRequest[];
  offers?: OfferStreamRequest[];
}
