/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */

/**
 * Flow type
 */
export type StreamObjectType =
  (typeof StreamObjectType)[keyof typeof StreamObjectType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StreamObjectType = {
  forced: 'forced',
  regular: 'regular',
  default: 'default',
} as const;
