/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */

export interface StreamAction {
  key?: string;
  name?: string;
  field?: string;
  type?: string;
  description?: string;
}
