/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */

export type StreamOfferSelection =
  (typeof StreamOfferSelection)[keyof typeof StreamOfferSelection];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StreamOfferSelection = {
  before_click: 'before_click',
  after_click: 'after_click',
} as const;
