/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */
import type { StreamFilterModes } from './streamFilterModes';

export interface StreamFilter {
  /** Filter Name */
  value?: string;
  /** Filter Description */
  tooltip?: string;
  modes?: StreamFilterModes;
  /** Group ID. It's used to group filters in a filters dropdown menu. */
  group?: string;
  /** HTML code for rendering filter body view (Not recommended to use) */
  template?: string;
  /** HTML code for rendering filter body view (Not recommended to use) */
  header_template?: string;
  /** Default values */
  defaults?: string;
}
