/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */

export type StreamObjectSchema =
  (typeof StreamObjectSchema)[keyof typeof StreamObjectSchema];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StreamObjectSchema = {
  landings: 'landings',
  redirect: 'redirect',
  action: 'action',
} as const;
