/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */
import type { StreamObject } from './streamObject';
import type { StreamRequestAllOf } from './streamRequestAllOf';

export type StreamRequest = StreamObject &
  StreamRequestAllOf &
  Required<
    Pick<
      StreamObject & StreamRequestAllOf,
      'campaign_id' | 'schema' | 'type' | 'name' | 'action_type'
    >
  >;
