/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */
import type { StreamActionOptions } from './streamActionOptions';
import type { StreamActionPayload } from './streamActionPayload';
import type { Filter } from './filter';
import type { Trigger } from './trigger';
import type { LandingStream } from './landingStream';
import type { OfferStream } from './offerStream';
import type { StreamOfferSelection } from './streamOfferSelection';

export interface Stream {
  id?: number;
  type?: string;
  name?: string;
  campaign_id?: number;
  position?: number;
  weight?: number;
  action_options?: StreamActionOptions;
  comments?: string;
  state?: string;
  updated_at?: string;
  action_type?: string;
  action_payload?: StreamActionPayload;
  schema?: string;
  collect_clicks?: boolean;
  filter_or?: boolean;
  filters?: Filter[];
  triggers?: Trigger[];
  landings?: LandingStream[];
  offers?: OfferStream[];
  offer_selection?: StreamOfferSelection;
}
