/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */
import type { StreamObject } from './streamObject';

export type StreamRequestPut = StreamObject;
