/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */

/**
 * State of the flow
 */
export type StreamObjectState =
  (typeof StreamObjectState)[keyof typeof StreamObjectState];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StreamObjectState = {
  active: 'active',
  disabled: 'disabled',
  deleted: 'deleted',
} as const;
