/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */

export interface Time {
  date?: string;
  timezone_type?: number;
  timezone?: string;
}
