/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */
import type { TriggersStreamRequestCondition } from './triggersStreamRequestCondition';
import type { TriggersStreamRequestTarget } from './triggersStreamRequestTarget';
import type { TriggersStreamRequestAction } from './triggersStreamRequestAction';

export interface TriggersStreamRequest {
  /** Trigger ID. */
  id?: number;
  /** Flow ID */
  stream_id: number;
  /** Condition */
  condition: TriggersStreamRequestCondition;
  /** Target */
  target: TriggersStreamRequestTarget;
  /** The URL of the Page to Check */
  selected_page?: string;
  /** Text Pattern to Check */
  pattern?: string;
  /** Action */
  action: TriggersStreamRequestAction;
  /** Interval between Checks */
  interval?: number;
  /** URLs for replacement (split by \n) */
  alternative_urls?: string;
  /** URL of the page that contains a new URL */
  grab_from_page?: string;
  /** Settings for AV Scanners */
  av_settings?: string;
  /** Perform also in a reverse mode (true/false) */
  reverse?: boolean;
  /** Tell AV scanner to scan the page content */
  scan_page?: boolean;
}
