/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */

export interface Trigger {
  id?: number;
  oid?: number;
  stream_id?: number;
  taget?: string;
  condition?: string;
  selected_page?: string;
  pattern?: string;
  action?: string;
  interval?: number;
  next_run_at?: number;
  alternative_urls?: string;
  grab_from_page?: string;
  av_settings?: string;
  reverse?: boolean;
  enabled?: boolean;
  scan_page?: boolean;
}
