/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */

/**
 * Condition
 */
export type TriggersStreamRequestCondition =
  (typeof TriggersStreamRequestCondition)[keyof typeof TriggersStreamRequestCondition];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TriggersStreamRequestCondition = {
  not_respond: 'not_respond',
  always: 'always',
  not_contains: 'not_contains',
  av_detected: 'av_detected',
} as const;
