/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */

/**
 * Action
 */
export type TriggersStreamRequestAction =
  (typeof TriggersStreamRequestAction)[keyof typeof TriggersStreamRequestAction];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TriggersStreamRequestAction = {
  disable: 'disable',
  replace_url: 'replace_url',
  grab_from_page: 'grab_from_page',
} as const;
