/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */

/**
 * Target
 */
export type TriggersStreamRequestTarget =
  (typeof TriggersStreamRequestTarget)[keyof typeof TriggersStreamRequestTarget];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TriggersStreamRequestTarget = {
  stream: 'stream',
  landings: 'landings',
  offers: 'offers',
  selected_page: 'selected_page',
} as const;
