/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */
import type { Error } from './error';

/**
 * Access denied
 */
export type UnauthorizedResponse = Error;
