/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */

/**
 * User type
 */
export type UserRequestUpdateType =
  (typeof UserRequestUpdateType)[keyof typeof UserRequestUpdateType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserRequestUpdateType = {
  USER: 'USER',
  ADMIN: 'ADMIN',
} as const;
