/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */

/**
 * User language
 */
export type UserPreferencesLanguage =
  (typeof UserPreferencesLanguage)[keyof typeof UserPreferencesLanguage];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserPreferencesLanguage = {
  ru: 'ru',
  en: 'en',
} as const;
