/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */
import type { UserAccessData } from './userAccessData';
import type { UserRequestAccessAccessDataAllOf } from './userRequestAccessAccessDataAllOf';

export type UserRequestAccessAccessData = UserAccessData &
  UserRequestAccessAccessDataAllOf;
