/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */
import type { UserRequestAccessAccessData } from './userRequestAccessAccessData';

export interface UserRequestAccess {
  access_data?: UserRequestAccessAccessData;
}
