/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */
import type { UserRequestUpdateType } from './userRequestUpdateType';
import type { UserPreferences } from './userPreferences';

export interface UserRequestUpdate {
  /** User login */
  login?: string;
  /** User password */
  new_password?: string;
  /** User password repeat */
  new_password_confirmation?: string;
  /** User type */
  type?: UserRequestUpdateType;
  /** API keys count */
  keyCount?: number;
  /** User preferences */
  preferences?: UserPreferences;
}
