/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */

/**
 * Flows access type
 */
export type UserAccessDataStreamsAccessType =
  (typeof UserAccessDataStreamsAccessType)[keyof typeof UserAccessDataStreamsAccessType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserAccessDataStreamsAccessType = {
  full_access: 'full_access',
  read_only: 'read_only',
  to_groups_and_selected: 'to_groups_and_selected',
  created_by_user_groups_and_selected: 'created_by_user_groups_and_selected',
} as const;
