/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */

/**
 * User type
 */
export type UserType = (typeof UserType)[keyof typeof UserType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserType = {
  USER: 'USER',
  ADMIN: 'ADMIN',
} as const;
