/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */
import type { UserType } from './userType';
import type { UserAccessDataProperty } from './userAccessDataProperty';
import type { UserPreferences } from './userPreferences';

export interface User {
  /** User ID */
  id?: number;
  /** User login */
  login?: string;
  /** User type */
  type?: UserType;
  access_data?: UserAccessDataProperty;
  /** User preferences */
  preferences?: UserPreferences;
}
