/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */

export type UserAccessDataPropertyAllOf = {
  /** Available resources */
  resources?: string[];
  /** Allowed resources */
  allowed_resources?: string[];
  /** Allowed reports */
  reports?: string[];
};
