/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */
import type { UserAccessDataResourcesItem } from './userAccessDataResourcesItem';
import type { UserAccessDataOffersAccessType } from './userAccessDataOffersAccessType';
import type { UserAccessDataCampaignsAccessType } from './userAccessDataCampaignsAccessType';
import type { UserAccessDataLandingsAccessType } from './userAccessDataLandingsAccessType';
import type { UserAccessDataTrafficSourcesAccessType } from './userAccessDataTrafficSourcesAccessType';
import type { UserAccessDataStreamsAccessType } from './userAccessDataStreamsAccessType';
import type { UserAccessDataAffiliateNetworksAccessType } from './userAccessDataAffiliateNetworksAccessType';
import type { UserAccessDataDomainsAccessType } from './userAccessDataDomainsAccessType';

/**
 * User access data
 */
export interface UserAccessData {
  resources?: UserAccessDataResourcesItem[];
  /** Offers access type */
  offers_access_type?: UserAccessDataOffersAccessType;
  /** Campaigns access type */
  campaigns_access_type?: UserAccessDataCampaignsAccessType;
  /** Landing pages access type */
  landings_access_type?: UserAccessDataLandingsAccessType;
  /** Traffic sources access type */
  traffic_sources_access_type?: UserAccessDataTrafficSourcesAccessType;
  /** Flows access type */
  streams_access_type?: UserAccessDataStreamsAccessType;
  /** Affiliate networks access type */
  affiliate_networks_access_type?: UserAccessDataAffiliateNetworksAccessType;
  /** Domains access type */
  domains_access_type?: UserAccessDataDomainsAccessType;
  /** List of available ID offers */
  offers_selected_entities?: number[];
  /** List of available ID campaigns */
  campaigns_selected_entities?: number[];
  /** List of available ID landings */
  landings_selected_entities?: number[];
  /** List of available ID traffic sources */
  traffic_sources_selected_entities?: number[];
  /** List of available ID affiliate networks */
  affiliate_networks_selected_entities?: number[];
  /** List of available ID domains */
  domains_selected_entities?: number[];
  /** List of available group ID */
  offers_selected_groups?: number[];
  /** List of available groups ID */
  campaigns_selected_groups?: number[];
  /** List of available groups ID */
  landings_selected_groups?: number[];
  /** List of available groups ID */
  traffic_sources_selected_groups?: number[];
  /** List of available groups ID */
  affiliate_networks_selected_groups?: number[];
  /** List of available group ID */
  domains_selected_groups?: number[];
  /** List of fields to which access is restricted */
  reports?: string[];
}
