/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */
import type { UserRequestType } from './userRequestType';
import type { UserPreferences } from './userPreferences';

export interface UserRequest {
  /** User login */
  login: string;
  /** User password */
  new_password: string;
  /** Repeat user password */
  new_password_confirmation: string;
  /** User type */
  type: UserRequestType;
  /** User preferences */
  preferences?: UserPreferences;
}
