/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */
import { z as zod } from 'zod';

import { fetcher } from '../../../utils/fetcher';

/**
 * Retrieve rows from the bot list
 * @summary Retrieve rows from the bot list
 */
export const getBotlistResponse = zod.object({
  value: zod.string().optional().describe('Rows'),
});

/**
 * Update the bot list
 * @summary Update the bot list
 */
export const putBotlistBody = zod.object({
  value: zod.string().describe('List of IPs. Example, 1.2.3.4\n2.3.4.5'),
});

export const putBotlistResponse = zod.object({
  count: zod.number().optional(),
});

/**
 * Add IPs to the bot list
 * @summary Add IPs to the bot list
 */
export const postBotlistAddBody = zod.object({
  value: zod.string().describe('List of IPs. Example, 1.2.3.4\n2.3.4.5'),
});

export const postBotlistAddResponse = zod.object({
  count: zod.number().optional(),
});

/**
 * Remove IPs from the bot list
 * @summary Remove IPs from the bot list
 */
export const postBotlistExcludeBody = zod.object({
  value: zod.string().describe('List of IPs. Example, 1.2.3.4\n2.3.4.5'),
});

export const postBotlistExcludeResponse = zod.object({
  count: zod.number().optional(),
});
