/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Keitaro Admin API
 * OpenAPI spec version: v1
 */
import { z as zod } from 'zod';

import { fetcher } from '../../../utils/fetcher';

/**
 * Returns a list all affiliate networks.
 * @summary List all affiliate networks
 */
export const getAffiliateNetworksResponseStateDefault = 'active';

export const getAffiliateNetworksResponseItem = zod.object({
  id: zod.number().optional(),
  name: zod.string().optional(),
  postback_url: zod.string().optional(),
  offer_param: zod.string().optional(),
  state: zod
    .enum(['active', 'deleted'])
    .default(getAffiliateNetworksResponseStateDefault),
  template_name: zod.string().optional(),
  notes: zod.string().optional(),
  pull_api_options: zod.string().optional(),
  created_at: zod.string().optional(),
  updated_at: zod.string().optional(),
  offers: zod.number().optional(),
});
export const getAffiliateNetworksResponse = zod.array(
  getAffiliateNetworksResponseItem
);

/**
 * Create an affiliate network
 * @summary Create an affiliate network
 */
export const postAffiliateNetworksBody = zod
  .object({
    name: zod.string().optional().describe('Affiliate network name'),
    postback_url: zod
      .string()
      .optional()
      .describe('Postback URL for the Affiliate network'),
    offer_param: zod
      .string()
      .optional()
      .describe(
        'These params are appends to offer URLs. Example, \"sub1={subid}&sub2={campaign_name}\"'
      ),
    notes: zod
      .string()
      .optional()
      .describe('User Notes for the Affiliate network'),
  })
  .and(zod.object({}));

export const postAffiliateNetworksResponseStateDefault = 'active';

export const postAffiliateNetworksResponse = zod.object({
  id: zod.number().optional(),
  name: zod.string().optional(),
  postback_url: zod.string().optional(),
  offer_param: zod.string().optional(),
  state: zod
    .enum(['active', 'deleted'])
    .default(postAffiliateNetworksResponseStateDefault),
  template_name: zod.string().optional(),
  notes: zod.string().optional(),
  pull_api_options: zod.string().optional(),
  created_at: zod.string().optional(),
  updated_at: zod.string().optional(),
  offers: zod.number().optional(),
});

/**
 * Retrieve affiliate metwork details
 * @summary Retrieve Affiliate network details
 */
export const getAffiliateNetworksIdParams = zod.object({
  id: zod.number().describe('Affiliate network ID'),
});

export const getAffiliateNetworksIdResponseStateDefault = 'active';

export const getAffiliateNetworksIdResponse = zod.object({
  id: zod.number().optional(),
  name: zod.string().optional(),
  postback_url: zod.string().optional(),
  offer_param: zod.string().optional(),
  state: zod
    .enum(['active', 'deleted'])
    .default(getAffiliateNetworksIdResponseStateDefault),
  template_name: zod.string().optional(),
  notes: zod.string().optional(),
  pull_api_options: zod.string().optional(),
  created_at: zod.string().optional(),
  updated_at: zod.string().optional(),
  offers: zod.number().optional(),
});

/**
 * Update an Affiliate network
 * @summary Update Affiliate network
 */
export const putAffiliateNetworksIdParams = zod.object({
  id: zod.number().describe('Affiliate network ID'),
});

export const putAffiliateNetworksIdBody = zod.object({
  name: zod.string().optional().describe('Affiliate network name'),
  postback_url: zod
    .string()
    .optional()
    .describe('Postback URL for the Affiliate network'),
  offer_param: zod
    .string()
    .optional()
    .describe(
      'These params are appends to offer URLs. Example, \"sub1={subid}&sub2={campaign_name}\"'
    ),
  notes: zod
    .string()
    .optional()
    .describe('User Notes for the Affiliate network'),
});

export const putAffiliateNetworksIdResponseStateDefault = 'active';

export const putAffiliateNetworksIdResponse = zod.object({
  id: zod.number().optional(),
  name: zod.string().optional(),
  postback_url: zod.string().optional(),
  offer_param: zod.string().optional(),
  state: zod
    .enum(['active', 'deleted'])
    .default(putAffiliateNetworksIdResponseStateDefault),
  template_name: zod.string().optional(),
  notes: zod.string().optional(),
  pull_api_options: zod.string().optional(),
  created_at: zod.string().optional(),
  updated_at: zod.string().optional(),
  offers: zod.number().optional(),
});

/**
 * Move affiliate network to the archive
 * @summary Move affiliate network to the archive
 */
export const deleteAffiliateNetworksIdParams = zod.object({
  id: zod.number().describe('Affiliate network ID'),
});

export const deleteAffiliateNetworksIdResponseStateDefault = 'active';

export const deleteAffiliateNetworksIdResponse = zod.object({
  id: zod.number().optional(),
  name: zod.string().optional(),
  postback_url: zod.string().optional(),
  offer_param: zod.string().optional(),
  state: zod
    .enum(['active', 'deleted'])
    .default(deleteAffiliateNetworksIdResponseStateDefault),
  template_name: zod.string().optional(),
  notes: zod.string().optional(),
  pull_api_options: zod.string().optional(),
  created_at: zod.string().optional(),
  updated_at: zod.string().optional(),
  offers: zod.number().optional(),
});

/**
 * Clone affiliate network
 * @summary Clone affiliate network
 */
export const postAffiliateNetworksIdCloneParams = zod.object({
  id: zod.number().describe('Affiliate network ID'),
});

export const postAffiliateNetworksIdCloneResponseStateDefault = 'active';

export const postAffiliateNetworksIdCloneResponse = zod.object({
  id: zod.number().optional(),
  name: zod.string().optional(),
  postback_url: zod.string().optional(),
  offer_param: zod.string().optional(),
  state: zod
    .enum(['active', 'deleted'])
    .default(postAffiliateNetworksIdCloneResponseStateDefault),
  template_name: zod.string().optional(),
  notes: zod.string().optional(),
  pull_api_options: zod.string().optional(),
  created_at: zod.string().optional(),
  updated_at: zod.string().optional(),
  offers: zod.number().optional(),
});

/**
 * Restore a affiliate network
 * @summary Restore affiliate network
 */
export const postAffiliateNetworksIdRestoreParams = zod.object({
  id: zod.number().describe('Affiliate network ID'),
});

/**
 * Get deleted affiliate networks
 * @summary Get deleted affiliate networks
 */
export const getAffiliateNetworksDeletedResponseStateDefault = 'active';

export const getAffiliateNetworksDeletedResponseItem = zod.object({
  id: zod.number().optional(),
  name: zod.string().optional(),
  postback_url: zod.string().optional(),
  offer_param: zod.string().optional(),
  state: zod
    .enum(['active', 'deleted'])
    .default(getAffiliateNetworksDeletedResponseStateDefault),
  template_name: zod.string().optional(),
  notes: zod.string().optional(),
  pull_api_options: zod.string().optional(),
  created_at: zod.string().optional(),
  updated_at: zod.string().optional(),
  offers: zod.number().optional(),
});
export const getAffiliateNetworksDeletedResponse = zod.array(
  getAffiliateNetworksDeletedResponseItem
);
